networks:
  bms-network:
    external: true

services:
  bms-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: "bms-db"
      DB_PORT: 3306
      DB_USERNAME: "root"
      DB_PASSWORD: "admin"
      DB_NAME: "bms"
      DB_SYNCHRONIZE: "false"
    depends_on:
      - mysql-db
    networks:
      - bms-network

  bms-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bms
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - bms-network